services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  fraud_pipeline:
    build: .
    container_name: fraud_pipeline
    depends_on:
      - kafka
    volumes:
      - ./storage:/app/storage
      - ./:/app
    command: python -m pipelines.run_pipeline

  # kafdrop:
  #   image: obsidiandynamics/kafdrop
  #   container_name: kafdrop
  #   depends_on:
  #     - kafka
  #   environment:
  #     KAFKA_BROKERCONNECT: kafka:9092
  #     JVM_OPTS: "-Xms32M -Xmx64M"
  #   ports:
  #     - "9000:9000"
  spark:
    image: spark:3.5.7-java17-python3
    container_name: spark
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark
      - SPARK_MASTER_PORT=7077
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark_jobs:/app/spark_jobs
    tty: true
    stdin_open: true
    # Force the master to bind to 0.0.0.0 so workers can connect
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark

  spark-worker:
    image: spark:3.5.7-java17-python3
    # container_name: spark-worker
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
    volumes:
      - ./spark_jobs:/app/spark_jobs
    # Explicitly tell the worker where the master is
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077

  dashboard:
    image: spark:3.5.7-java17-python3
    container_name: fraud_dashboard
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - SPARK_MASTER=spark://spark:7077
    command: tail -f /dev/null
    
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9000:9000"
      - "9870:9870"
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      - namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - SERVICE_PRECONDITION=namenode:9870 # Ensures datanode waits for namenode UI
    ports:
      - "9864:9864"
